//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace passwordManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("passwordManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Sheviak Kyrylo 2018.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        public static string btbClc {
            get {
                return ResourceManager.GetString("btbClc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM.
        /// </summary>
        public static string btnAccent {
            get {
                return ResourceManager.GetString("btnAccent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string btnAddNew {
            get {
                return ResourceManager.GetString("btnAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items.
        /// </summary>
        public static string btnAllItem {
            get {
                return ResourceManager.GetString("btnAllItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string btnArchive {
            get {
                return ResourceManager.GetString("btnArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        public static string btnClc {
            get {
                return ResourceManager.GetString("btnClc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string btnFavorites {
            get {
                return ResourceManager.GetString("btnFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string btnIN {
            get {
                return ResourceManager.GetString("btnIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string btnInfo {
            get {
                return ResourceManager.GetString("btnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRATION.
        /// </summary>
        public static string btnRegistr {
            get {
                return ResourceManager.GetString("btnRegistr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        public static string btnUP {
            get {
                return ResourceManager.GetString("btnUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Username.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string lblNote {
            get {
                return ResourceManager.GetString("lblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPass {
            get {
                return ResourceManager.GetString("lblPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply password.
        /// </summary>
        public static string lblPassReply {
            get {
                return ResourceManager.GetString("lblPassReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRATION.
        /// </summary>
        public static string lblRegistr {
            get {
                return ResourceManager.GetString("lblRegistr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string lblWeb {
            get {
                return ResourceManager.GetString("lblWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW.
        /// </summary>
        public static string titleFormAdd {
            get {
                return ResourceManager.GetString("titleFormAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT ITEM.
        /// </summary>
        public static string titleFormEdit {
            get {
                return ResourceManager.GetString("titleFormEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password manager.
        /// </summary>
        public static string titleProgram {
            get {
                return ResourceManager.GetString("titleProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string toolTipBlock {
            get {
                return ResourceManager.GetString("toolTipBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string toolTipCopy {
            get {
                return ResourceManager.GetString("toolTipCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete item.
        /// </summary>
        public static string toolTipDel {
            get {
                return ResourceManager.GetString("toolTipDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit item.
        /// </summary>
        public static string toolTipEdit {
            get {
                return ResourceManager.GetString("toolTipEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string toolTipSysClose {
            get {
                return ResourceManager.GetString("toolTipSysClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn.
        /// </summary>
        public static string toolTipSysTurn {
            get {
                return ResourceManager.GetString("toolTipSysTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to website.
        /// </summary>
        public static string toolTipWebsite {
            get {
                return ResourceManager.GetString("toolTipWebsite", resourceCulture);
            }
        }
    }
}
